server:
  port: 8080

api:
  ticket-base-url: http://ticket-service:8082

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: mainuser
    password: password
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
